/**
 * Data export utilities — CSV and basic PDF (via print dialog)
 */

import type { EtsyListing, OptimizationRecord, SaleRecord } from '@/types'
import { formatDate, formatCurrency } from './utils'

// ─── CSV ──────────────────────────────────────────────────────────────────────

function csvRow(values: (string | number | boolean | undefined | null)[]): string {
  return values.map(v => {
    const s = String(v ?? '')
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s
  }).join(',')
}

function downloadCSV(filename: string, rows: string[]) {
  const csv = rows.join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function exportListingsCSV(listings: EtsyListing[]) {
  const headers = csvRow(['Title', 'State', 'Price', 'Views', 'Favorites', 'Sales', 'Grade', 'Image Grade', 'Images', 'Tags', 'Optimizations', 'Created', 'Last Optimized'])
  const rows = listings.map(l => csvRow([
    l.title,
    l.state,
    l.price,
    l.views,
    l.favorites,
    l.sales_count,
    l.current_grade ?? '',
    l.current_image_grade ?? '',
    l.image_urls.length,
    l.tags.length,
    l.optimization_count,
    formatDate(l.etsy_created_at),
    l.last_optimized_at ? formatDate(l.last_optimized_at) : 'Never',
  ]))
  downloadCSV(`radariq-listings-${new Date().toISOString().split('T')[0]}.csv`, [headers, ...rows])
}

export function exportOptimizationsCSV(records: OptimizationRecord[]) {
  const headers = csvRow(['Listing', 'Status', 'Original Grade', 'New Grade', 'Improvement', 'Model', 'Date', 'Rejection Reason'])
  const rows = records.map(r => csvRow([
    r.listing_title,
    r.status,
    r.original_grade,
    r.new_grade ?? '',
    r.grade_improvement ?? '',
    r.model_used,
    formatDate(r.created_at),
    r.rejection_reason ?? '',
  ]))
  downloadCSV(`radariq-optimizations-${new Date().toISOString().split('T')[0]}.csv`, [headers, ...rows])
}

export function exportSalesCSV(sales: SaleRecord[]) {
  const headers = csvRow(['Listing', 'Sale Date', 'Price', 'Qty', 'Grade at Sale', 'Image Grade at Sale', 'Optimizations at Sale'])
  const rows = sales.map(s => csvRow([
    s.listing_title,
    formatDate(s.sale_date),
    s.sale_price,
    s.quantity_sold,
    s.listing_grade_at_sale ?? '',
    s.image_grade_at_sale ?? '',
    s.optimization_count_at_sale,
  ]))
  downloadCSV(`radariq-sales-${new Date().toISOString().split('T')[0]}.csv`, [headers, ...rows])
}

// ─── PDF (print dialog) ───────────────────────────────────────────────────────
// Opens a print-friendly page — user can save as PDF from browser.

export function exportAnalyticsPDF(shopName: string, stats: {
  avgGrade: number
  totalListings: number
  totalOptimizations: number
  salesMonth: number
  revenueMonth: number
}) {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Radar IQ Analytics Report — ${shopName}</title>
      <style>
        body { font-family: sans-serif; color: #081515; padding: 40px; }
        h1 { color: #7c3aed; }
        .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }
        .card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }
        .value { font-size: 28px; font-weight: bold; color: #7c3aed; }
        .label { font-size: 12px; color: #64748b; margin-top: 4px; }
        .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; }
      </style>
    </head>
    <body>
      <h1>Radar IQ Analytics Report</h1>
      <p><strong>${shopName}</strong> · Generated ${new Date().toLocaleDateString()}</p>
      <div class="grid">
        <div class="card"><div class="value">${stats.totalListings}</div><div class="label">Active Listings</div></div>
        <div class="card"><div class="value">${stats.avgGrade}/100</div><div class="label">Average Listing Grade</div></div>
        <div class="card"><div class="value">${stats.totalOptimizations}</div><div class="label">Total Optimizations</div></div>
        <div class="card"><div class="value">${stats.salesMonth}</div><div class="label">Sales This Month</div></div>
        <div class="card"><div class="value">${formatCurrency(stats.revenueMonth)}</div><div class="label">Revenue This Month</div></div>
      </div>
      <p class="footer">Report generated by Radar IQ. Data is for this Etsy seller account only.</p>
    </body>
    </html>
  `
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.print()
}
